# https://pnpm.io/settings
packages:
  - '.'

trustPolicy: off
blockExoticSubdeps: true
preferFrozenLockfile: true
verifyStoreIntegrity: true

overrides:
  sharp: 0.35.5
  source-map-js: 1.2.2

allowBuilds:
  '@changesets/cli': true
  canvas: true
  gitleaks-secret-scanner: true
  lefthook: true
  sharp: true
  unrs-resolver: true
