# https://pnpm.io/settings
packages:
  - '.'

trustPolicy: off
blockExoticSubdeps: true
preferFrozenLockfile: true
verifyStoreIntegrity: true

allowBuilds:
  '@changesets/cli': true
  canvas: true
  gitleaks-secret-scanner: true
  lefthook: true
  sharp: true
  unrs-resolver: true
